spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:h2:tcp://localhost/~/test12W
    username: sa
    password:
    driver-class-name: org.h2.Driver

jwt:
  secret: MDwwDQYJKoZIhvcNAQEBBQADKwAwKAIhAJjRrypsSsCrHKNgbK1ncwMjMDwwDQYJKoZShvcNAQEBBQADKwAwKLI

token:
  expire:
    time: 1800000 # 1000 * 60 * 30 => 1800000